.PHONY: all signup generate backup recover signeth signsol

all: main

signup:
	go run cmd/signup/main.go

generate:
	go run cmd/generate/main.go

backup:
	go run cmd/backup/main.go

recover:
	go run cmd/recover/main.go

signeth:
	go run cmd/ethSign/main.go

main:
	go run .
